" Search
set incsearch
set ignorecase
set smartcase

" Status bar: mode, partial command
set showmode
set showcmd

" Timeout for mapped key sequences
set timeout
set timeoutlen=200

" Number of lines to scroll with U & D
" Scroll offset, Relative numbers
set scroll=10
set scrolloff=3
set relativenumber

" Basic mappings
let mapleader = " "
inoremap kj <esc>
map ; $

" Use Q for formatting instead of ex-mode
map Q gq

" --------------------------------

" Show position in status bar
set ruler 

" Copy indent from current line while moving to next line
set autoindent 

" Do not wrap lines
set nowrap 

" Auto reload file if changed outside
set autoread 

" Normal backspace in insert mode
set backspace=2 

" No sounds
set belloff=all 

" Show tabs line
set showtabline=2 

" Tab settings
set tabstop=2
set shiftwidth=2
set expandtab

" Colors setting for terminal
set termguicolors 

" Wildmenu
set wildmenu
set wildmode=longest:full,full
" --------------------------------

colorscheme molokai 
syntax on

" Mappings
nnoremap <leader>r {gq}
nnoremap <leader>e gq$

" Makes switching windows easier
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" Automatically change directory in vim
set autochdir
let g:netrw_fastbrowse = 0
autocmd FileType netrw setl bufhidden=wipe

" Load CP environment
command CP source $CP_COMMON_UTIL_DIR/vim/cp.vim

" Text Formatting environment
command TF set textwidth=64 linebreak

" --------------------------------
