syntax on
set encoding=utf-8

" Basic mappings
let mapleader = " "
inoremap kj <esc>
vnoremap kj <esc>
map ; $

nnoremap <leader>d :bd!<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>p ggdG"+p
nnoremap <leader>y gg"+yG
nnoremap <leader>o :only<CR> " Hide other windows for same buffer
nnoremap <C-o> :ls<CR>:b
nnoremap <C-[> :bp<CR>
nnoremap <C-]> :bn<CR>

" Makes switching windows easier
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" Use Q for formatting instead of ex-mode
map Q gq

map <leader>D :put =strftime('%Y-%m-%d %H:%M:%S')<CR>

" No swap files
set noswapfile

set background=light

set list
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+

" Allow unsaved buffers
set hidden

" Search
set incsearch
set ignorecase
set smartcase

" Status bar: mode, partial command
set showmode
set showcmd

" Timeout for mapped key sequences
set timeout
set timeoutlen=200

" Number of lines to scroll with U & D
" Scroll offset, Relative numbers
set scroll=10
set scrolloff=3
set relativenumber

" Show position in status bar
set ruler

" Copy indent from current line while moving to next line
set autoindent

" Do not wrap lines
set nowrap

" Auto reload file if changed outside
set autoread 

" Normal backspace in insert mode
set backspace=2 

" No sounds
set belloff=all 

" Show tabs line
set showtabline=2 

" Tab settings
set tabstop=2
set shiftwidth=2
set expandtab

" Colors setting for terminal
set termguicolors 

" Wildmenu
set wildmenu
set wildmode=longest:full,full

set lazyredraw

" Plugins
source ~/vimfiles/plugins.vim

" For CP
source ~/vimfiles/cp.vim

